{
 "title": "快充曲线统计",
 "tags": [
  "battery",
  "简体中文",
  "只读增强"
 ],
 "time": { "from": "now-1M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "car_id",
    "label": "车辆",
    "query": "SELECT\n    id as __value,\n    CASE WHEN COUNT(id) OVER (PARTITION BY name) > 1 AND name IS NOT NULL THEN CONCAT(name, ' - ', RIGHT(vin, 6)) ELSE COALESCE(name, CONCAT('VIN ', vin)) end as __text \nFROM cars\nORDER BY display_priority ASC, name ASC, vin ASC;"
   },
   {
    "name": "base_url",
    "label": "此部分需要配置名为\"家\"和\"公司\"的地理围栏并设置费用，以便准确计算充电成本。",
    "query": "select base_url from settings limit 1;"
   },
   { "name": "filter_power_from", "label": "功率 >=", "query": "0" },
   { "name": "filter_power_to", "label": "功率 <=", "query": "260" },
   { "name": "filter_soc_from", "label": "电量 >=", "query": "0" },
   { "name": "filter_soc_to", "label": "电量 <=", "query": "100" }
  ]
 },
 "panels": [
  {
   "title": "超级充电站充电曲线",
   "type": "xychart",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  c.battery_level as \"电量 [%]\",\r\n  round(avg(c.charger_power), 0) AS \"功率 [kW]\",\r\n  c.charging_process_id as \"充电进程ID\",\r\n  COALESCE(g.name, a.name) || ' ' || to_char(c.date, 'YYYY-MM-dd') as \"充电\",\r\n  p.start_date as \"开始日期\",\r\n  p.end_date as \"结束日期\"\r\nFROM\r\n  charges c\r\nJOIN charging_processes p ON p.id = c.charging_process_id \r\nJOIN addresses a ON a.id = p.address_id\r\nLEFT JOIN geofences g ON g.id = p.geofence_id\r\nWHERE\r\n  $__timeFilter(date)\r\n AND p.car_id = $car_id\r\n AND c.battery_level >= $filter_soc_from AND c.battery_level <= $filter_soc_to\r\n AND charger_power >= $filter_power_from AND charger_power <= $filter_power_to\r\n AND c.fast_charger_present\r\n AND (COALESCE(g.name, a.name) ILIKE '%supercharger%' OR COALESCE(g.name, a.name) ILIKE '%超级充电%') \r\nGROUP BY c.battery_level, c.charging_process_id, a.name, g.name, p.start_date, p.end_date, to_char(c.date, 'YYYY-MM-dd')"
    },
    {
     "rawSql": "SELECT\n  c.battery_level as \"B - 电量 [%]\",\n  PERCENTILE_CONT(0.5) WITHIN GROUP(ORDER BY charger_power) as \"B - 平均功率 [kW]\"\nFROM\n  charges c\nJOIN charging_processes p ON p.id = c.charging_process_id \nJOIN addresses a ON a.id = p.address_id\nLEFT JOIN geofences g ON g.id = p.geofence_id\nWHERE\n  $__timeFilter(date)\n AND p.car_id = $car_id\n AND c.battery_level >= $filter_soc_from AND c.battery_level <= $filter_soc_to\n AND charger_power >= $filter_power_from AND charger_power <= $filter_power_to\n AND c.fast_charger_present\n AND (COALESCE(g.name, a.name) ILIKE '%supercharger%' OR COALESCE(g.name, a.name) ILIKE '%超级充电%') \nGROUP BY c.battery_level"
    }
   ]
  },
  {
   "title": "其他直流充电曲线",
   "type": "xychart",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  c.battery_level as \"电量 [%]\",\r\n  round(avg(c.charger_power), 0) AS \"功率 [kW]\",\r\n  c.charging_process_id as \"充电进程ID\",\r\n  COALESCE(g.name, a.name) || ' ' || to_char(c.date, 'YYYY-MM-dd') as \"充电\",\r\n  p.start_date as \"开始日期\",\r\n  p.end_date as \"结束日期\"\r\nFROM\r\n  charges c\r\nJOIN charging_processes p ON p.id = c.charging_process_id \r\nJOIN addresses a ON a.id = p.address_id\r\nLEFT JOIN geofences g ON g.id = p.geofence_id\r\nWHERE\r\n  $__timeFilter(date)\r\n AND p.car_id = $car_id\r\n AND c.battery_level >= $filter_soc_from AND c.battery_level <= $filter_soc_to\r\n AND charger_power >= $filter_power_from AND charger_power <= $filter_power_to\r\n AND c.fast_charger_present\r\n AND COALESCE(g.name, a.name) NOT ILIKE '%supercharger%' AND COALESCE(g.name, a.name) NOT ILIKE '%超级充电%' \r\nGROUP BY c.battery_level, c.charging_process_id, a.name, g.name, p.start_date, p.end_date, to_char(c.date, 'YYYY-MM-dd')"
    },
    {
     "rawSql": "SELECT\n  c.battery_level as \"B - 电量 [%]\",\n  PERCENTILE_CONT(0.5) WITHIN GROUP(ORDER BY charger_power) as \"B - 平均功率 [kW]\"\nFROM\n  charges c\nJOIN charging_processes p ON p.id = c.charging_process_id \nJOIN addresses a ON a.id = p.address_id\nLEFT JOIN geofences g ON g.id = p.geofence_id\nWHERE\n  $__timeFilter(date)\n AND p.car_id = $car_id\n AND c.battery_level >= $filter_soc_from AND c.battery_level <= $filter_soc_to\n AND charger_power >= $filter_power_from AND charger_power <= $filter_power_to\n AND c.fast_charger_present\n AND COALESCE(g.name, a.name) NOT ILIKE '%supercharger%' AND COALESCE(g.name, a.name) NOT ILIKE '%超级充电%' \nGROUP BY c.battery_level"
    }
   ]
  },
  { "title": "快充会话", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "type": "piechart",
   "description": "本仪表盘用于查看特斯拉超级充电站和其他直流充电站的充电曲线。",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH charges_summary AS (\n    SELECT\n        cp.id,\n        COALESCE(geo.name, CONCAT_WS(', ', COALESCE(addr.name, nullif(CONCAT_WS(' ', addr.road, addr.house_number), '')), addr.city)) AS location,\n        COUNT(c.charging_process_id)\n    FROM charging_processes cp\n    LEFT JOIN \n        addresses addr ON addr.id = address_id\n    LEFT JOIN\n        geofences geo ON geo.id = geofence_id\n    LEFT JOIN\n        charges c ON cp.id = c.charging_process_id\n    WHERE\n        $__timeFilter(date) AND\n        cp.car_id = $car_id AND cp.charge_energy_added > 0.01 AND c.fast_charger_present \n    GROUP BY 1, 2\n)\nSELECT \n    CASE\n        WHEN location ILIKE '%supercharger%' THEN '特斯拉超级充电站'\n        ELSE '其他直流充电站' END AS location,\n    COUNT(location) AS n\nFROM charges_summary\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "最大功率",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 15 },
   "targets": [
    {
     "rawSql": "WITH power_summary AS (\n    SELECT ROUND(MAX(charges.charger_power) / 5, 0) * 5 AS \"power\"\n    FROM charging_processes\n    LEFT JOIN charges ON charging_processes.id = charges.charging_process_id\n    WHERE $__timeFilter(date) AND charging_processes.car_id = $car_id AND charging_processes.charge_energy_added > 0.01 AND charges.fast_charger_present\n    GROUP BY charging_processes.id\n)\nSELECT power_summary.power AS \"功率 [kW]\", COUNT(power_summary.power) AS n\nFROM power_summary\nWHERE power_summary.power >= $filter_power_from AND power_summary.power <= $filter_power_to\nGROUP BY 1\nORDER BY 1 DESC\n"
    }
   ]
  }
 ]
}