apiVersion: 1

datasources:
  - name: TeslaMate
    uid: TeslaMate
    type: postgres
    url: $GRAFANA_DATABASE_HOST:$GRAFANA_DATABASE_PORT
    user: $GRAFANA_DATABASE_USER
    access: proxy
    basicAuth: false
    withCredentials: false
    isDefault: true
    editable: false
    secureJsonData:
      password: $GRAFANA_DATABASE_PASS
    jsonData:
      postgresVersion: 1800
      sslmode: $GRAFANA_DATABASE_SSL_MODE
      database: $GRAFANA_DATABASE_NAME
    version: 1
